name = "Coyote"
license = "MIT"
licenselink = "https://github.com/nightswinger/hugo-theme-coyote/blob/main/LICENSE"
description = "Card-based blog theme for Hugo"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/nightswinger/hugo-theme-coyote"

# If you have a running demo of the theme.
demosite = "https://nightswinger.github.io/hugo-theme-coyote/"

tags = ["blog"]
features = ["awesome", "card"]

min_version = "0.101.0"

# If the theme has a single author
[author]
    name = "nightswinger"
    homepage = "https://github.com/nightswinger"
